// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**
	 *  Reads device identity and management state from the local machine
	 *  for the onboarding "Will scan" strip. Runs the same
	 *  `device-info.ps1` that the audit pipeline dot-sources, so the
	 *  pre-scan strip and the post-scan top bar agree on what they show.
	 * 
	 *  Wrapped in `spawn_blocking` because the PowerShell spawn blocks the
	 *  thread — the Tauri runtime stays free to serve other IPC during the
	 *  few-hundred-millisecond startup.
	 */
	getDeviceInfo: () => typedError<DeviceInfo, string>(__TAURI_INVOKE("get_device_info")),
	/**
	 *  Parses the CIS benchmark PDF at `path` and returns a fully-populated
	 *  `Baseline` for the frontend to render.
	 * 
	 *  Runs the (CPU-heavy) parse on the blocking-thread pool so the Tauri
	 *  runtime stays free to serve UI events. Streams `ParserProgress` events
	 *  over `on_progress` as each pipeline stage starts.
	 */
	parseBaseline: (path: string, onProgress: Channel<ParserProgress>) => typedError<Baseline, string>(__TAURI_INVOKE("parse_baseline", { path, onProgress })),
	loadAppState: () => typedError<{
	activeBaselineSha: string | null,
	preferences?: Preferences,
} | null, string>(__TAURI_INVOKE("load_app_state")),
	saveAppState: (state: AppState) => typedError<null, string>(__TAURI_INVOKE("save_app_state", { state })),
	loadUserState: (baselineSha: string) => typedError<{
	baselineSha256: string,
	exceptions: { [key in string]: Exception },
	notes: { [key in string]: Note },
} | null, string>(__TAURI_INVOKE("load_user_state", { baselineSha })),
	saveUserState: (state: UserState) => typedError<null, string>(__TAURI_INVOKE("save_user_state", { state })),
	loadCachedBaseline: (sha: string) => typedError<{
	baseline: Baseline,
	/**
	 *  True when the cached baseline was produced by a different parser
	 *  version than the one currently running.
	 */
	isStale: boolean,
} | null, string>(__TAURI_INVOKE("load_cached_baseline", { sha })),
	/**
	 *  Returns the dashboard's scan-related state for a baseline: the
	 *  most-recent full `Scan`, the per-rec change log, and the
	 *  per-scan summary history. Each sub-file is loaded independently;
	 *  failures land in `errors` instead of taking down the whole load.
	 */
	loadScanContext: (baselineSha: string) => typedError<ScanContextLoad, string>(__TAURI_INVOKE("load_scan_context", { baselineSha })),
	/**
	 *  Deletes the most-recent full `Scan` file for `baseline_sha`. Used
	 *  by the recovery flow when the file is unreadable or the user wants
	 *  to clear it manually from settings. Missing file is treated as
	 *  success so the call is idempotent.
	 */
	resetLatestScan: (baselineSha: string) => typedError<null, string>(__TAURI_INVOKE("reset_latest_scan", { baselineSha })),
	/**
	 *  Deletes the trend-chart summary history for `baseline_sha`. The
	 *  next scan starts a fresh history.
	 */
	resetSummaries: (baselineSha: string) => typedError<null, string>(__TAURI_INVOKE("reset_summaries", { baselineSha })),
	/**
	 *  Deletes the per-rec change log for `baseline_sha`. The next scan
	 *  that flips a rec records the first event under the fresh log.
	 */
	resetChanges: (baselineSha: string) => typedError<null, string>(__TAURI_INVOKE("reset_changes", { baselineSha })),
	/**
	 *  Clears all scans, history, and annotations for `baseline_sha`,
	 *  keeping the parsed baseline loaded.
	 */
	clearBaselineData: (baselineSha: string) => typedError<null, string>(__TAURI_INVOKE("clear_baseline_data", { baselineSha })),
	/**
	 *  Removes `baseline_sha` entirely — its data, its parsed cache, and
	 *  its active-baseline pointer — so the app returns to onboarding.
	 */
	removeBaseline: (baselineSha: string) => typedError<null, string>(__TAURI_INVOKE("remove_baseline", { baselineSha })),
	/**
	 *  Runs the audit pipeline against the device this dashboard is on:
	 *  generates (or reuses) a cached `audit.ps1` from `baseline`, spawns
	 *  `powershell.exe` to execute it, and streams each `ScanRecord` over
	 *  `on_record` as it lands. Returns the assembled `Scan` once the script
	 *  finishes, after persisting it to disk.
	 */
	startScan: (baseline: Baseline, onRecord: Channel<ScanRecord>) => typedError<Scan, string>(__TAURI_INVOKE("start_scan", { baseline, onRecord })),
	/**
	 *  Requests cancellation of the in-flight scan by creating the active
	 *  run's cooperative-cancel sentinel. The audit script stops at its
	 *  next recommendation boundary and the run resolves as cancelled
	 *  without persisting. A no-op when no scan is running.
	 */
	cancelScan: () => typedError<null, string>(__TAURI_INVOKE("cancel_scan")),
	/**
	 *  Application version string (from `Cargo.toml`) for the settings
	 *  readout.
	 */
	appVersion: () => __TAURI_INVOKE<string>("app_version"),
	/**
	 *  Opens the appdata directory in the OS file manager. Creates it
	 *  first so a fresh install with no scans yet still opens cleanly.
	 */
	openDataDir: () => typedError<null, string>(__TAURI_INVOKE("open_data_dir")),
	/**
	 *  Writes pre-rendered export `contents` to `dest_path`. The CSV/JSON
	 *  body is composed on the frontend, where effective status,
	 *  exceptions, notes, and the human-readable strings already exist and
	 *  match the console one-to-one; this stays a thin, format-agnostic
	 *  file write so there's no second copy of that logic in Rust.
	 */
	writeExport: (destPath: string, contents: string) => typedError<null, string>(__TAURI_INVOKE("write_export", { destPath, contents })),
};

/* Types */
/**
 *  Cross-baseline application state, persisted as `app_state.json`. Tracks
 *  which baseline (if any) the dashboard should reopen on next launch and
 *  user-level UI preferences that don't belong to any single baseline.
 */
export type AppState = {
	activeBaselineSha: string | null,
	preferences?: Preferences,
};

export type Assessment = "Automated" | "Manual";

export type AuditPolicyMode = "NoAuditing" | "Success" | "Failure" | "SuccessAndFailure";

export type AuditProcedure = 
// One or more registry checks; ALL must pass.
{ type: "Registry"; checks: RegistryCheck[] } | 
// Intune MDM PolicyManager (two-step WinningProvider lookup).
{ type: "PolicyManager"; scope: PolicyScope; area: string; setting: string; expected: ExpectedValue } | 
// User Rights Assignment (audited via secedit /export → [Privilege Rights]).
{ type: "UserRightsAssignment"; rightName: string; expected: Principal[]; matching: MatchMode } | 
// Account Policies / Security Options (audited via secedit /export).
{ type: "Secedit"; section: SeceditSection; setting: string; expected: ExpectedValue } | 
// Audit subcategory via auditpol /get /subcategory:"{GUID}".
{ type: "AuditPolicy"; subcategoryGuid: string; expected: AuditPolicyMode; matching: MatchMode } | 
// No automated audit available.
{ type: "Manual"; description: string };

export type Baseline = {
	source: BaselineSource,
	categories: Category[],
	recommendations: Recommendation[],
};

export type BaselineSource = {
	benchmarkName: string,
	benchmarkVersion: string,
	pdfFilename: string,
	pdfSha256: string,
	parsedAt: string,
	parserVersion: string,
};

/**
 *  Wraps a cached `Baseline` with a staleness flag so the frontend can
 *  surface a re-parse prompt without making a second IPC round-trip.
 */
export type CachedBaseline = {
	baseline: Baseline,
	/**
	 *  True when the cached baseline was produced by a different parser
	 *  version than the one currently running.
	 */
	isStale: boolean,
};

export type Category = {
	number: string,
	name: string,
	parent: string | null,
};

/**
 *  One status flip detected at scan time. Appended to `changes.jsonl`
 *  whenever a rec's status differs from its prior recorded value.
 *  `from_status` is `None` for the first observation of a rec (no prior
 *  value to compare against). The frontend reads the most recent event
 *  per rec to drive persistent delta indicators — the flag stays
 *  "regressed" or "improved" until another event for the same rec
 *  supersedes it, regardless of how many no-op rescans happen between.
 */
export type ChangeEvent = {
	recId: string,
	fromStatus: Status | null,
	toStatus: Status,
	observedAt: string,
	parserVersion: string,
	auditScriptVersion: string,
};

/**
 *  One row in the per-rec check breakdown. Mirrors the `checks` array
 *  shape emitted by `ps/audit.ps1`. `actual` is `None` when the value
 *  was absent at scan time. `pass` is `None` for `Manual` recs where
 *  there's no automated verdict.
 */
export type CheckDetail = {
	path: string,
	valueName: string,
	expected: string,
	actual: string | null,
	pass: boolean | null,
};

/**
 *  Console table row spacing. `Comfortable` is the roomier default;
 *  `Compact` tightens row padding so more recommendations fit on
 *  screen for admin scanning.
 */
export type Density = "comfortable" | "compact";

export type DeviceInfo = {
	hostname: string,
	osName: string,
	osVersion: string,
	osBuild: string,
	managedBy: Management,
};

/**
 *  An accepted-risk decision against a single recommendation. Excluded
 *  from the In-scope pass rate and counted toward Strict compliance;
 *  the reason and grantor are surfaced in the detail drawer.
 */
export type Exception = {
	reason: string,
	grantedAt: string,
	grantedBy: string | null,
};

export type ExpectedValue = { type: "Equals"; value: Value } | { type: "NotEquals"; value: Value } | { type: "AtLeast"; value: number } | { type: "AtMost"; value: number } | { type: "OneOf"; values: Value[] } | { type: "Contains"; substring: string } | { type: "ContainsAll"; substrings: string[] } | { type: "Absent" } | { type: "AbsentOr"; inner: ExpectedValue } | { type: "All"; values: ExpectedValue[] } | { type: "Any"; values: ExpectedValue[] };

export type Level = "L1" | "L2" | "BL";

export type Management = {
	intune: boolean,
	groupPolicy: boolean,
};

export type MatchMode = 
// Title says `is set to 'X'` — actual must equal `X` exactly.
"Exact" | 
/**
 *  Title says `is set to include 'X'` / `to include 'X'` — actual must
 *  contain `X` (so e.g. URA principals can be a superset, AuditPolicy
 *  `Success` recs pass when actual is `SuccessAndFailure`).
 */
"Includes";

/**
 *  Free-form context attached to a recommendation. Doesn't affect status or
 *  scoring; survives across scans of the same baseline.
 */
export type Note = {
	text: string,
	updatedAt: string,
};

/**
 *  Stages emitted by `parse_with_progress` so the UI can render a status
 *  label and progress bar. `ExtractingText` and `Classifying` carry
 *  `(done, total)` so the bar can move continuously through the slow
 *  phases; the other stages are instantaneous.
 */
export type ParserProgress = { stage: "readingFile" } | { stage: "computingChecksum" } | { stage: "extractingText"; done: number; total: number } | { stage: "slicingRecommendations" } | { stage: "classifying"; done: number; total: number } | { stage: "complete" };

export type PolicyScope = "Device" | "User";

// User-level UI preferences that survive baseline switches.
export type Preferences = {
	theme?: Theme,
	timeFormat?: TimeFormat,
	density?: Density,
};

export type Principal = {
	identifier: string,
	kind: PrincipalKind,
};

export type PrincipalKind = "Sid" | "WellKnownName" | "AccountName";

export type Recommendation = {
	id: string,
	level: Level,
	categoryNumber: string,
	title: string,
	description: string,
	rationale: string | null,
	impact: string | null,
	assessment: Assessment,
	audit: AuditProcedure,
	remediation: Remediation | null,
	references: Reference[],
};

export type Reference = { type: "Url"; url: string } | { type: "Note"; text: string };

export type RegistryCheck = {
	path: string,
	valueName: string,
	expected: ExpectedValue,
	scope: RegistryScope,
};

export type RegistryScope = 
// HKLM — applies to the machine.
"Machine" | 
// HKU\[USER SID]\... — applies to the currently-logged-in user only.
"CurrentUser";

export type Remediation = {
	description: string,
	settingsCatalogPath: string | null,
	defaultValue: string | null,
};

export type Scan = {
	baselineSha256: string,
	startedAt: string,
	finishedAt: string | null,
	device: DeviceInfo,
	results: { [key in string]: ScanResult },
	error: string | null,
	/**
	 *  Snapshot of `PARSER_VERSION` at scan time. Lets the UI detect when
	 *  a saved scan was produced under a different parser/script schema
	 *  before drawing cross-scan comparisons (deltas, trend chart).
	 */
	parserVersion: string,
	/**
	 *  Snapshot of `AUDIT_SCRIPT_VERSION` at scan time. Same intent as
	 *  `parser_version` — captures the schema half that the audit script
	 *  owns (status enum, check shape, NDJSON contract).
	 */
	auditScriptVersion: string,
};

/**
 *  Bundles the scan-related state for a baseline as the dashboard
 *  needs it. `latest` drives current-scan rendering; `changes` powers
 *  per-rec delta indicators with persistence (a flag stays until the
 *  rec actually flips again, not just until the next no-op rescan);
 *  `summaries` feeds the trend chart and headline math.
 */
export type ScanContext = {
	latest: Scan | null,
	changes: ChangeEvent[],
	summaries: ScanSummary[],
};

/**
 *  IPC return shape for `load_scan_context`. Combines the loaded
 *  scan-related state with per-sub-file load errors so the frontend can
 *  degrade per-surface (empty state for a missing latest scan, inline
 *  notice on the trend chart for a broken summaries file, etc.) rather
 *  than going dark on a single bad file.
 */
export type ScanContextLoad = {
	context: ScanContext,
	errors: ScanLoadErrors,
};

/**
 *  Per-sub-file load outcome for `load_scan_context`. Each field is
 *  `None` when the corresponding file loaded clean (or didn't exist) and
 *  `Some(message)` when it failed — the frontend uses this to render
 *  per-surface failure notices instead of one global banner.
 */
export type ScanLoadErrors = {
	latest: string | null,
	changes: string | null,
	summaries: string | null,
};

/**
 *  One line from the audit script's NDJSON stdout. Parsed by the runner
 *  and forwarded to merge + frontend before being collapsed into a
 *  `ScanResult` keyed by `id`.
 */
export type ScanRecord = {
	id: string,
	status: Status,
	measuredAt: string,
	currentValue: string | null,
	expected: string | null,
	checks: CheckDetail[] | null,
	error: string | null,
};

export type ScanResult = {
	status: Status,
	currentValue: string | null,
	/**
	 *  Human-readable description of what the check expected, formatted
	 *  by the PS script. Surfaced alongside `current_value` in the UI so
	 *  users can see "wanted X, got Y" without opening the baseline JSON.
	 */
	expected: string | null,
	/**
	 *  Per-check structured breakdown: one entry per `RegistryCheck` for
	 *  Registry recs, or a single conceptual row for the other variants.
	 *  The drawer renders this as a Path / Value / Expected / Found table.
	 */
	checks: CheckDetail[] | null,
	error: string | null,
	measuredAt: string,
};

/**
 *  Lightweight per-scan record for the trend chart and headline
 *  math. Kept separate from full `Scan` files so we can show months of
 *  history without growing storage materially — counts mean the same
 *  thing across schema versions, so old summaries stay readable even
 *  when the underlying scan format evolves.
 */
export type ScanSummary = {
	startedAt: string,
	finishedAt: string | null,
	pass: number,
	fail: number,
	manual: number,
	error: number,
	/**
	 *  Count of Fail results that carry a matching entry in the user's
	 *  exception list at scan time. Held separately from `fail` so the
	 *  trend math can exclude accepted exceptions from the In-scope
	 *  rate, matching the level cards.
	 */
	exception: number,
	parserVersion: string,
	auditScriptVersion: string,
};

export type SeceditSection = 
// Account Policies (Rename Guest, password policy, etc.).
{ type: "SystemAccess" } | 
// Security Options exposed via UI but no separate registry path.
{ type: "RegistryValues" } | 
// System Services.
{ type: "Service" } | 
// Escape hatch for sections we encounter outside the above.
{ type: "Other"; name: string };

export type Status = "Pass" | "Fail" | "Manual" | "Error";

/**
 *  Color scheme preference. `System` follows the OS via the webview's
 *  `prefers-color-scheme`; `Light` / `Dark` pin the theme regardless.
 */
export type Theme = "system" | "light" | "dark";

/**
 *  Clock display preference for rendered timestamps. `TwentyFourHour`
 *  shows `14:30`; `TwelveHour` shows `2:30 PM`. Date parts are
 *  unaffected.
 */
export type TimeFormat = "24h" | "12h";

/**
 *  Per-baseline user annotations, persisted as
 *  `user_states/{baseline_sha256}.json`. Loading re-creates the maps; an
 *  absent file means a fresh baseline with no annotations yet.
 */
export type UserState = {
	baselineSha256: string,
	exceptions: { [key in string]: Exception },
	notes: { [key in string]: Note },
};

export type Value = { type: "Dword"; value: number } | { type: "QDword"; value: number } | { type: "Str"; value: string } | { type: "MultiStr"; values: string[] } | { type: "Binary"; bytes: number[] };

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

