// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	hello: () => __TAURI_INVOKE<Hello>("hello"),
	/**
	 *  Parses the CIS benchmark PDF at `path` and returns a fully-populated
	 *  `Baseline` for the frontend to render.
	 * 
	 *  Runs the (CPU-heavy) parse on the blocking-thread pool so the Tauri
	 *  runtime stays free to serve UI events. Streams `ParserProgress` events
	 *  over `on_progress` as each pipeline stage starts.
	 */
	parseBaseline: (path: string, onProgress: Channel<ParserProgress>) => typedError<Baseline, string>(__TAURI_INVOKE("parse_baseline", { path, onProgress })),
	loadAppState: () => typedError<{
	activeBaselineSha: string | null,
} | null, string>(__TAURI_INVOKE("load_app_state")),
	saveAppState: (state: AppState) => typedError<null, string>(__TAURI_INVOKE("save_app_state", { state })),
	loadUserState: (baselineSha: string) => typedError<{
	baselineSha256: string,
	exceptions: { [key in string]: Exception },
	notes: { [key in string]: Note },
} | null, string>(__TAURI_INVOKE("load_user_state", { baselineSha })),
	saveUserState: (state: UserState) => typedError<null, string>(__TAURI_INVOKE("save_user_state", { state })),
	loadCachedBaseline: (sha: string) => typedError<{
	baseline: Baseline,
	/**
	 *  True when the cached baseline was produced by a different parser
	 *  version than the one currently running.
	 */
	isStale: boolean,
} | null, string>(__TAURI_INVOKE("load_cached_baseline", { sha })),
	/**
	 *  Returns the chronologically-latest `Scan` saved for `baseline_sha`,
	 *  or `null` when no scans have run yet. Lets the dashboard rehydrate
	 *  the user's last results on launch without forcing a rescan.
	 */
	loadMostRecentScan: (baselineSha: string) => typedError<{
	baselineSha256: string,
	startedAt: string,
	finishedAt: string | null,
	device: DeviceInfo,
	results: { [key in string]: ScanResult },
	error: string | null,
} | null, string>(__TAURI_INVOKE("load_most_recent_scan", { baselineSha })),
	/**
	 *  Runs the audit pipeline against the device this dashboard is on:
	 *  generates (or reuses) a cached `audit.ps1` from `baseline`, spawns
	 *  `powershell.exe` to execute it, and streams each `ScanRecord` over
	 *  `on_record` as it lands. Returns the assembled `Scan` once the script
	 *  finishes, after persisting it to disk.
	 */
	startScan: (baseline: Baseline, onRecord: Channel<ScanRecord>) => typedError<Scan, string>(__TAURI_INVOKE("start_scan", { baseline, onRecord })),
};

/* Types */
/**
 *  Cross-baseline application state, persisted as `app_state.json`. Tracks
 *  which baseline (if any) the dashboard should reopen on next launch.
 */
export type AppState = {
	activeBaselineSha: string | null,
};

export type Assessment = "Automated" | "Manual";

export type AuditPolicyMode = "NoAuditing" | "Success" | "Failure" | "SuccessAndFailure";

export type AuditProcedure = 
// One or more registry checks; ALL must pass.
{ type: "Registry"; checks: RegistryCheck[] } | 
// Intune MDM PolicyManager (two-step WinningProvider lookup).
{ type: "PolicyManager"; scope: PolicyScope; area: string; setting: string; expected: ExpectedValue } | 
// User Rights Assignment (audited via secedit /export → [Privilege Rights]).
{ type: "UserRightsAssignment"; rightName: string; expected: Principal[]; matching: MatchMode } | 
// Account Policies / Security Options (audited via secedit /export).
{ type: "Secedit"; section: SeceditSection; setting: string; expected: ExpectedValue } | 
// Audit subcategory via auditpol /get /subcategory:"{GUID}".
{ type: "AuditPolicy"; subcategoryGuid: string; expected: AuditPolicyMode; matching: MatchMode } | 
// No automated audit available.
{ type: "Manual"; description: string };

export type Baseline = {
	source: BaselineSource,
	categories: Category[],
	recommendations: Recommendation[],
};

export type BaselineSource = {
	benchmarkName: string,
	benchmarkVersion: string,
	pdfFilename: string,
	pdfSha256: string,
	parsedAt: string,
	parserVersion: string,
};

/**
 *  Wraps a cached `Baseline` with a staleness flag so the frontend can
 *  surface a re-parse prompt without making a second IPC round-trip.
 */
export type CachedBaseline = {
	baseline: Baseline,
	/**
	 *  True when the cached baseline was produced by a different parser
	 *  version than the one currently running.
	 */
	isStale: boolean,
};

export type Category = {
	number: string,
	name: string,
	parent: string | null,
};

/**
 *  One row in the per-rec check breakdown. Mirrors the `checks` array
 *  shape emitted by `ps/audit.ps1`. `actual` is `None` when the value
 *  was absent at scan time. `pass` is `None` for `Manual` recs where
 *  there's no automated verdict.
 */
export type CheckDetail = {
	path: string,
	valueName: string,
	expected: string,
	actual: string | null,
	pass: boolean | null,
};

export type DeviceInfo = {
	hostname: string,
	osName: string,
	osVersion: string,
	osBuild: string,
	managedBy: Management,
};

/**
 *  An accepted-risk decision against a single recommendation. Counted as a
 *  pass for the In-scope score; the reason and grantor are surfaced in the
 *  detail drawer.
 */
export type Exception = {
	reason: string,
	grantedAt: string,
	grantedBy: string | null,
};

export type ExpectedValue = { type: "Equals"; value: Value } | { type: "NotEquals"; value: Value } | { type: "AtLeast"; value: number } | { type: "AtMost"; value: number } | { type: "OneOf"; values: Value[] } | { type: "Contains"; substring: string } | { type: "ContainsAll"; substrings: string[] } | { type: "Absent" } | { type: "AbsentOr"; inner: ExpectedValue } | { type: "All"; values: ExpectedValue[] } | { type: "Any"; values: ExpectedValue[] };

export type Hello = {
	msg: string,
};

export type Level = "L1" | "L2" | "BL";

export type Management = {
	intune: boolean,
	groupPolicy: boolean,
};

export type MatchMode = 
// Title says `is set to 'X'` — actual must equal `X` exactly.
"Exact" | 
/**
 *  Title says `is set to include 'X'` / `to include 'X'` — actual must
 *  contain `X` (so e.g. URA principals can be a superset, AuditPolicy
 *  `Success` recs pass when actual is `SuccessAndFailure`).
 */
"Includes";

/**
 *  Free-form context attached to a recommendation. Doesn't affect status or
 *  scoring; survives across scans of the same baseline.
 */
export type Note = {
	text: string,
	updatedAt: string,
};

/**
 *  Stages emitted by `parse_with_progress` so the UI can render a status
 *  label and progress bar.
 */
export type ParserProgress = { stage: "readingFile" } | { stage: "computingChecksum" } | { stage: "extractingText" } | { stage: "slicingRecommendations" } | { stage: "classifying"; done: number; total: number } | { stage: "complete" };

export type PolicyScope = "Device" | "User";

export type Principal = {
	identifier: string,
	kind: PrincipalKind,
};

export type PrincipalKind = "Sid" | "WellKnownName" | "AccountName";

export type Recommendation = {
	id: string,
	level: Level,
	categoryNumber: string,
	title: string,
	description: string,
	rationale: string | null,
	impact: string | null,
	assessment: Assessment,
	audit: AuditProcedure,
	remediation: Remediation | null,
	references: Reference[],
};

export type Reference = { type: "Url"; url: string } | { type: "Note"; text: string };

export type RegistryCheck = {
	path: string,
	valueName: string,
	expected: ExpectedValue,
	scope: RegistryScope,
};

export type RegistryScope = 
// HKLM — applies to the machine.
"Machine" | 
// HKU\[USER SID]\... — applies to the currently-logged-in user only.
"CurrentUser";

export type Remediation = {
	description: string,
	settingsCatalogPath: string | null,
	defaultValue: string | null,
};

export type Scan = {
	baselineSha256: string,
	startedAt: string,
	finishedAt: string | null,
	device: DeviceInfo,
	results: { [key in string]: ScanResult },
	error: string | null,
};

/**
 *  One line from the audit script's NDJSON stdout. Parsed by the runner
 *  and forwarded to merge + frontend before being collapsed into a
 *  `ScanResult` keyed by `id`.
 */
export type ScanRecord = {
	id: string,
	status: Status,
	measuredAt: string,
	currentValue: string | null,
	expected: string | null,
	checks: CheckDetail[] | null,
	error: string | null,
};

export type ScanResult = {
	status: Status,
	currentValue: string | null,
	/**
	 *  Human-readable description of what the check expected, formatted
	 *  by the PS script. Surfaced alongside `current_value` in the UI so
	 *  users can see "wanted X, got Y" without opening the baseline JSON.
	 */
	expected: string | null,
	/**
	 *  Per-check structured breakdown: one entry per `RegistryCheck` for
	 *  Registry recs, or a single conceptual row for the other variants.
	 *  The drawer renders this as a Path / Value / Expected / Found table.
	 */
	checks: CheckDetail[] | null,
	error: string | null,
	measuredAt: string,
};

export type SeceditSection = 
// Account Policies (Rename Guest, password policy, etc.).
{ type: "SystemAccess" } | 
// Security Options exposed via UI but no separate registry path.
{ type: "RegistryValues" } | 
// System Services.
{ type: "Service" } | 
// Escape hatch for sections we encounter outside the above.
{ type: "Other"; name: string };

export type Status = "Pass" | "Fail" | "Manual" | "Error";

/**
 *  Per-baseline user annotations, persisted as
 *  `user_states/{baseline_sha256}.json`. Loading re-creates the maps; an
 *  absent file means a fresh baseline with no annotations yet.
 */
export type UserState = {
	baselineSha256: string,
	exceptions: { [key in string]: Exception },
	notes: { [key in string]: Note },
};

export type Value = { type: "Dword"; value: number } | { type: "QDword"; value: number } | { type: "Str"; value: string } | { type: "MultiStr"; values: string[] } | { type: "Binary"; bytes: number[] };

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

