// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	hello: () => __TAURI_INVOKE<Hello>("hello"),
};

/* Types */
export type Assessment = "Automated" | "Manual";

export type AuditPolicyMode = "NoAuditing" | "Success" | "Failure" | "SuccessAndFailure";

export type AuditProcedure = 
// One or more registry checks; ALL must pass.
{ type: "Registry"; checks: RegistryCheck[] } | 
// Intune MDM PolicyManager (two-step WinningProvider lookup).
{ type: "PolicyManager"; scope: PolicyScope; area: string; setting: string; expected: ExpectedValue } | 
// User Rights Assignment (audited via secedit /export → [Privilege Rights]).
{ type: "UserRightsAssignment"; rightName: string; expected: Principal[] } | 
// Account Policies / Security Options (audited via secedit /export).
{ type: "Secedit"; section: SeceditSection; setting: string; expected: ExpectedValue } | 
// Audit subcategory via auditpol /get /subcategory:"{GUID}".
{ type: "AuditPolicy"; subcategoryGuid: string; expected: AuditPolicyMode } | 
// No automated audit available.
{ type: "Manual"; description: string };

export type Baseline = {
	source: BaselineSource,
	categories: Category[],
	recommendations: Recommendation[],
};

export type BaselineSource = {
	benchmarkName: string,
	benchmarkVersion: string,
	pdfFilename: string,
	pdfSha256: string,
	parsedAt: string,
	parserVersion: string,
};

export type Category = {
	number: string,
	name: string,
	parent: string | null,
};

export type ExpectedValue = { type: "Equals"; value: Value } | { type: "NotEquals"; value: Value } | { type: "AtLeast"; value: number } | { type: "AtMost"; value: number } | { type: "OneOf"; values: Value[] } | { type: "Contains"; substring: string } | { type: "ContainsAll"; substrings: string[] } | { type: "Absent" } | { type: "AbsentOr"; inner: ExpectedValue } | { type: "All"; values: ExpectedValue[] } | { type: "Any"; values: ExpectedValue[] };

export type Hello = {
	msg: string,
};

export type Level = "L1" | "L2" | "BL";

export type PolicyScope = "Device" | "User";

export type Principal = {
	identifier: string,
	kind: PrincipalKind,
};

export type PrincipalKind = "Sid" | "WellKnownName" | "AccountName";

export type Recommendation = {
	id: string,
	level: Level,
	categoryNumber: string,
	title: string,
	description: string,
	rationale: string | null,
	impact: string | null,
	assessment: Assessment,
	audit: AuditProcedure,
	remediation: Remediation | null,
	references: Reference[],
};

export type Reference = { type: "Url"; url: string } | { type: "Note"; text: string };

export type RegistryCheck = {
	path: string,
	valueName: string,
	expected: ExpectedValue,
	scope: RegistryScope,
};

export type RegistryScope = 
// HKLM — applies to the machine.
"Machine" | 
// HKU\[USER SID]\... — applies to the currently-logged-in user only.
"CurrentUser";

export type Remediation = {
	description: string,
	settingsCatalogPath: string | null,
	defaultValue: string | null,
};

export type SeceditSection = 
// Account Policies (Rename Guest, password policy, etc.).
{ type: "SystemAccess" } | 
// Security Options exposed via UI but no separate registry path.
{ type: "RegistryValues" } | 
// System Services.
{ type: "Service" } | 
// Escape hatch for sections we encounter outside the above.
{ type: "Other"; name: string };

export type Value = { type: "Dword"; value: number } | { type: "QDword"; value: number } | { type: "Str"; value: string } | { type: "MultiStr"; values: string[] } | { type: "Binary"; bytes: number[] };

